### ISSUE TITLE
Log Generation Pass Config File

### ISSUE THREAD

**Issue by alexanderrock** [iamnotturner/vaccipy#311]
Hi Zusammen,

aktuelle Version 1.1.4 per Batch Script gestartet.
Habe mehrere Konfigs for schleife startet für jede das Programm mit entsprechender Übergabe -f name.json

Fehler:
```
2021-06-03 23:30:29.056   impfterminservice   [inf] [*W2F5 | 88212]   103 Impfzentren verfügbar
2021-06-03 23:30:29.056   impfterminservice   [inf] [*W2F5 | 88212]   'Oberschwabenhalle Kreisimpfzentrum Ravensburg' in 88212 Ravensburg ausgewählt
2021-06-03 23:30:29.291   impfterminservice   [inf] [*W2F5 | 88212]   [L920] Altersgruppe: 16+ (Intervall: 40 Tage) --> ['BioNTech']
2021-06-03 23:30:29.307   impfterminservice   [inf] [*W2F5 | 88212]   [L921] Altersgruppe: 18+ (Intervall: 40 Tage) --> ['Moderna', 'BioNTech']
2021-06-03 23:30:29.322   impfterminservice   [inf] [*W2F5 | 88212]   [L922] Altersgruppe: 60+ (Intervall: 40 Tage) --> ['Moderna', 'BioNTech', 'AstraZeneca']
2021-06-03 23:30:29.322   impfterminservice   [inf] [*W2F5 | 88212]   [L923] Altersgruppe: 60+ (Intervall:  ? Tage) --> ['Johnson&Johnson']

2021-06-03 23:30:29.322   impfterminservice   [inf] [*W2F5 | 88212]   Browser-Cookies generieren
--- Logging error ---
Traceback (most recent call last):
  File "tools\utils.py", line 30, in wrapper
  File "tools\its.py", line 490, in renew_cookies
  File "tools\its.py", line 205, in get_chromedriver
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=91.0.4472.77)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\handlers.py", line 70, in emit
  File "logging\handlers.py", line 394, in doRollover
  File "logging\handlers.py", line 111, in rotate
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'D:\\IMPF\\vaccipy\\tools\\log\\impfterminservice.log' -> 'D:\\IMPF\\vaccipy\\tools\\log\\impfterminservice.log.2021-06-02'
Call stack:
  File "main.py", line 494, in <module>
  File "main.py", line 420, in main
  File "main.py", line 341, in subcommand_search
  File "main.py", line 202, in run_search_interactive
  File "main.py", line 235, in run_search
  File "tools\its.py", line 774, in terminsuche
  File "tools\utils.py", line 66, in wrapper
  File "tools\clog.py", line 144, in error
  File "logging\__init__.py", line 1471, in error
  File "logging\__init__.py", line 1585, in _log
  File "logging\__init__.py", line 1595, in handle
  File "logging\__init__.py", line 1657, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\handlers.py", line 73, in emit
Message: 'SessionNotCreatedException exception raised - retry 1'
Arguments: {'prefix': 'renew_cookies'}
2021-06-03 23:30:32.942   impfterminservice   [err] [renew_cookies]   SessionNotCreatedException exception raised - retry 1
```

Kann man das Logging je nach Übergebenem File machen /tools/logs/ÜBERGABEFILENAME.log?

Oder muss für jedes Config ein eigener Ordner mit erstellt werden? ^^

**Comment by iamnotturner** [comment]
hey, du kannst dir die `clog.py` selbst anpassen, einfacher wäre es einfach immer für jede Instanz das Datum an den Dateiname zu packen.
