### ISSUE TITLE
Buchung nach erfolgreicher Terminsuche nicht erfolgreich

### ISSUE THREAD

**Issue by fsteinhardt** [iamnotturner/vaccipy#415]
Ich hatte heute wohl ein Problem mit der Buchung eines gefundenen Termins:

```

2021-06-10 07:17:01.128   impfterminservice   [suc] [76137 76287 69123 75175 76646 68163 69124 75056]   Termin gefunden!
2021-06-10 07:17:01.131   impfterminservice   [suc] [76137 76287 69123 75175 76646 68163 69124 75056]   'Kreisimpfzentrum Sulzfeld' in 75056 Sulzfeld
2021-06-10 07:17:01.132   impfterminservice   [suc] [76137 76287 69123 75175 76646 68163 69124 75056]   1. Termin: 30.06.2021 um 12:24 Uhr
2021-06-10 07:17:01.132   impfterminservice   [suc] [76137 76287 69123 75175 76646 68163 69124 75056]   2. Termin: 11.08.2021 um 14:30 Uhr
2021-06-10 07:17:01.132   impfterminservice   [inf] [76137 76287 69123 75175 76646 68163 69124 75056]   Browser-Cookies generieren
2021-06-10 07:17:02.539   impfterminservice   [inf] [76137 76287 69123 75175 76646 68163 69124 75056]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-10 07:17:56.401   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Cookies können nicht generiert werden: Message: 

2021-06-10 07:17:56.402   impfterminservice   [inf] [76137 76287 69123 75175 76646 68163 69124 75056]   Starte zweiten Versuch über Selenium ...
2021-06-10 07:17:56.402   impfterminservice   [inf] [76137 76287 69123 75175 76646 68163 69124 75056]   Termin über Selenium buchen
2021-06-10 07:17:57.722   impfterminservice   [inf] [76137 76287 69123 75175 76646 68163 69124 75056]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-10 07:18:44.206   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Vermittlungscode kann nicht eingegeben werden: Message: 

2021-06-10 07:18:45.243   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Termine können nicht gesucht werden
2021-06-10 07:18:53.085   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Termine können nicht ausgewählt werden
2021-06-10 07:19:00.008   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Termine können nicht ausgewählt werden (Button)
2021-06-10 07:19:01.034   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   1. Daten können nicht erfasst werden
2021-06-10 07:19:02.062   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Kontaktdaten können nicht eingegeben werden
2021-06-10 07:19:08.997   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Button ÜBERNEHMEN kann nicht gedrückt werden
2021-06-10 07:19:10.025   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Button Termin buchen kann nicht gedrückt werden
2021-06-10 07:19:13.035   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Automatisierte Terminbuchung fehlgeschlagen
2021-06-10 07:19:13.035   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Termin manuell im Fenster oder im Browser buchen.
2021-06-10 07:19:13.035   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Link: https://001-iz.impfterminservice.de/impftermine/suche/AAAA-BBBB-CCCC/75056
2021-06-10 07:29:13.135   impfterminservice   [err] [76137 76287 69123 75175 76646 68163 69124 75056]   Termin konnte nicht gebucht werden.
Traceback (most recent call last):
  File "main.py", line 572, in <module>
    main()
  File "main.py", line 478, in main
    subcommand_search(args)
  File "main.py", line 390, in subcommand_search
    run_search(get_kontaktdaten(args.file), check_delay=args.retry_sec)
  File "main.py", line 283, in run_search
    ImpfterminService.terminsuche(
  File "/home/florian/vaccipy/tools/its.py", line 1044, in terminsuche
    its.notify(title="Terminbuchung:", message=msg)
TypeError: notify() got an unexpected keyword argument 'message'
```

Ich habe meinen Vermittlungscode oben im log geändert.

Das ist diese vaccipy-version aus dem beta branch:
```

commit 508743808a17f6032bb0006b33a15f599c512a79 (HEAD -> beta, origin/beta)
Author: Marco Rombach <36333308+marcorombach@users.noreply.github.com>
Date:   Wed Jun 9 22:59:18 2021 +0200

    feat(notification): added better validation (#400)
```

Ich lasse das unter Ubuntu 20.04 auf der Konsole laufen.

Die log-screenshots und html habe ich hier eingepackt (die slash/Backslashes sind in den Dateinamen zwischen Windows und Linux durcheinandergekommen, die Dateien sind aber lesbar):
[tools\log\error.zip](https://github.com/iamnotturner/vaccipy/files/6630232/tools.log.error.zip)

**Comment by marcorombach** [comment]
Ist vermutlich nicht die Ursache, aber ein Fehler der hier auftritt, ist, dass die notify Funktion mit dem Parameter message anstatt von msg aufgerufen wird.

**Comment by iamnotturner** [comment]
> dass die notify Funktion mit dem Parameter message anstatt von msg aufgerufen wird.

#416 fixed

> Ich lasse das unter Ubuntu 20.04 auf der Konsole laufen.

bei der Cookie-Generierung und Backup-Buchung läuft Selenium nicht Headless, sondern muss ein paar Klicks im Browserfenster machen. Das könnte die Ursache für dein Problem sein.

**Comment by fsteinhardt** [comment]
Ist das auch bei der Vermittlungscode-generierung so? Die hat so problemlos funktioniert, der Browser ist aufgegangen und wurde bedient.

**Comment by fsteinhardt** [comment]
Etwas genauer: Ubuntu läuft bei mir nicht headless, sondern in voller Gui. Ich habe nur nicht eine der vaccipy zips runtergeladen sondern das git repo geclont und in einem Terminalfenster python3 main.py gestartet.

**Comment by fsteinhardt** [comment]
Ich habe Ubuntus Auto-Screen-lock abgeschaltet, vielleicht hat das gestört. (Suspend war schon abgeschaltet)

Dann hatte ich mein repository geupdated auf 
```
commit e3d41c742c5c3886241ea4ef0ea3d66f7d554a11 (tag: v1.2.4)
Author: Tim Reibe <38082956+iamnotturner@users.noreply.github.com>
Date:   Thu Jun 10 12:06:33 2021 +0200

    refactored kwarg message to msg (#416)
```
und nochmal gestartet.

Mit diesen Änderungen hat vaccipy gerade wieder einen Termin gefunden und den diesmal auch buchen können.

Danke.

**Comment by iamnotturner** [comment]
> Mit diesen Änderungen hat vaccipy gerade wieder einen Termin gefunden und den diesmal auch buchen können.

super, damit hat sich das Problem von selbst gelöst. Vielen Dank für das Feedback!
