### ISSUE TITLE
Nach gescheiterter Terminbuchung - Error 486

### ISSUE THREAD

**Issue by nagel86** [iamnotturner/vaccipy#482]
Gibt wohl leider einen neuen Fehler Code....
Kurz Erklärung: Es wurde ein Termin gefunden, konnte aber nicht automatisch gebucht werden. Wollte es dann manuell machen, aber bekomme nach Eingabe des Codes nur noch die Meldung "Anspruch abgelaufen" und die Konsole zeigt mit den Status Code 486.

Ich werde (morgen) nochmal berichten ob der Code nun endgültig gesperrt wurde.

![error486](https://user-images.githubusercontent.com/19304002/122127957-3a7fb000-ce34-11eb-9463-5fd5090617e7.jpg)

**Comment by andoorius** [comment]
"Anspruch abgelaufen" bedeutet, dass mit diesem Vermittlungscode bereits 2x abgesagt wurde 
=> Code ist wertlos, weil er keine Buchungen mehr zulässt. 

https://www.impfterminservice.de/terminservice/faq -- letzte Frage:
"WIE SAGE ICH EINEN TERMIN AB?

Sie können den über den Menüpunkt "Buchung verwalten" oder telefonisch absagen. Im Anschluss können Sie gerne direkt einen neuen Termin buchen. Bitte beachten Sie dabei, dass Ihr Vermittlungscode ausschließlich für das in der Absagebestätigung genannte Impfzentrum gilt. Sie müssen dieses bei der nächsten Terminauswahl wieder auswählen. Sie können den Vermittlungscode einmal für eine weitere Terminbuchung verwenden. Beantworten Sie die Frage, ob eine Anspruchsprüfung bereits durchgeführt wurde mit "Ja" und geben sie Ihren Vermittlungscode in das vorgesehene Feld ein. Nach 2-maliger Absage Ihrer Termine verliert ein Vermittlungscode seine Gültigkeit.

Sollten Sie den zweiten Termin absagen müssen, buchen Sie rechtzeitig einen Ersatztermin telefonisch unter der 116117. "

**Comment by nagel86** [comment]
Ich hatte den Code aber erst heute generiert und entsprechend wurde noch kein Termin damit gebucht. Und es hätten ja auch keine Termine mit dem Code gefunden werden können.

**Comment by andoorius** [comment]
Hmmm verrückt - dann kann ich leider nicht helfen, sorry.

**Comment by nagel86** [comment]
Also die scheinen definitiv die Codes zu sperren. Exakt das selbe ist soeben mit einem weiteren Code passiert.

**Comment by andoorius** [comment]
Gehen die auch bei manueller Buchung? Ok - schwer zu testen, wenn es keine Termine gibt ...

**Comment by nagel86** [comment]
Könnte ich ja jetzt ohnehin nicht mehr mit den Codes testen, es kommt ja direkt nach der Eingabe der Codes "Anspruch abgelaufen".

Heute Mittag ging es noch. Da hatte ich auch den Fall, dass Termine gefunden, aber nicht automatisch gebucht werden konnten, manuell ging es dann aber ohne Probleme.

Tja und jetzt habe ich zwei mal den Fall, dass die manuelle Buchung nach fehlgeschlagener automatischer Buchung, nicht mehr geht.

**Comment by JonasMock** [comment]
@nagel86 Hast du die Mail und Handynummer bereits zuvor verwendet ?

Ansonsten ist es natürlich nicht besonders schwer für die Betreiber, alles zu sperren was zu einem Zeitpunkt generiert wurde, wo es eigentlich keine freien Termine gab. 😄

**Comment by nagel86** [comment]
jepp, Mail+Handynummer wurden mehrfach verwendet, war bisher aber nie ein Problem.

Wenn das aber das Kriterium wäre, würden ja all meine Codes die ich noch habe, nicht mehr funktionieren. Aber es funktionieren nur die beiden erwähnten nicht mehr, und das exakt nachdem versucht wurde die gefundenen Termine automatisch zu buchen

**Comment by JonasMock** [comment]
@nagel86 @andoorius Wäre auf jeden Fall interessant zu prüfen ob man mit den Codes trotzdem einen Termin buchen kann. Das Fenster aus deinem Screenshot kann man überspringen, wenn man die response vom Server entsprechend anpasst.

Kannst du die entsprechenden Codes und PLZ hier rein schicken ? Dann probiere ich das heute Nachmittag mal aus.

**Comment by nagel86** [comment]
Die Codes kann ich dir morgen gerne direkt zukommen lassen. Öffentlich poste ich die mal nicht, keine Ahnung welche Infos man aus den Codes ziehen kann ;)
und jetzt muss ich erstmal schlafen

**Comment by andoorius** [comment]
Ich hätte noch einen "unverbrauchten" Code von gestern 6:33Uhr mit dem GUI erzeugt - den müsste ja dann das gleiche Schicksal treffen. Kann ich gerne für Testzwecke weitergeben. Für das Klinikum Stgt.... oder auch selbst was Testen, wenn jemand ne gute Idee hat.
Wobei ich mir irgendwie schwer vorstellen kann, dass hier so viel Geld und Zeit in die Identifikation von "n.i.O" Vermittlungscodes gesteckt wird....am Ende wird sich jeder nur 2x Impfen lassen und es wird ja (hoffentlich!) niemand so bescheuert sein 5 Termine aus Langeweile zu buchen...
Mit etwas Geduld bekommt ja eh jeder sehr viele (m.E. unnötige) Vermittlungscodes. 

Unabhängig davon würde mich es auch sehr interessieren, was mit den Codes passiert ist.

**Comment by TRojaner2013** [comment]
Die Codes scheinen zumindest nicht von vorne erzeugung an ungültig zu sein. Ich konnte mir heute einen generieren und auch der von gestern morgen die funktioniert noch. Das die Betreiber Codes sperren, die Sie als Bot identifiziert habe kann ich mir zumindest vorstellen. Wobei einem meiner Codes dann seit gestern Nachmttag das selbe Schicklsal teilen müsste. Der Funktioniert aber noch -  zumindest kann ich mich damit einloggen und (keine) Termine sehen.

**Comment by nagel86** [comment]
Kurzes update: Codes können nach wie vor nicht über die Website verwendet werden, es kommt sofort "Anspruch abgelaufen". Habe eben nochmal die Suche mit vaccipy und den gleichen Codes angeworfen, das funktioniert soweit. Es können also wohl Termine damit gesucht aber nicht gebucht werden.

Mir ist allerdings noch etwas aufgefallen. Habe versehentlich für die gleiche Person mit dem gleichen Code im gleichen Impfzentrum (sprich mit der gleichen JSON config) die Suche zwei mal gestartet (so ist es halt wenn man irgendwann nachlässig wird). Vielleicht hat das auch (irgendwie) zu dem Problem geführt. Hier mal die beiden Logs:

```
2021-06-15 23:35:07.730   impfterminservice   [suc] [70376]   Termin gefunden!
2021-06-15 23:35:07.736   impfterminservice   [suc] [70376]   'Impfzentrum am Robert-Bosch-Krankenhaus' in 70376 Stuttgart
2021-06-15 23:35:07.736   impfterminservice   [suc] [70376]   1. Termin: 29.06.2021 um 19:45 Uhr
2021-06-15 23:35:07.736   impfterminservice   [suc] [70376]   2. Termin: 10.08.2021 um 15:10 Uhr
2021-06-15 23:35:07.737   impfterminservice   [suc] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/****-****-****/70376
2021-06-15 23:35:07.929   impfterminservice   [inf] [70376]   Browser-Cookies generieren
2021-06-15 23:35:08.967   impfterminservice   [inf] [70376]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-15 23:35:09.970   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (0, 0) nach (924, 432)
2021-06-15 23:35:25.610   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (924.0, 432.0) nach (432, 758)
2021-06-15 23:35:31.289   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (432.0, 758.0) nach (314, 247)
2021-06-15 23:35:41.592   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (314.0, 247.0) nach (222, 384)
2021-06-15 23:35:59.142   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (222.0, 384.0) nach (413, 450)
2021-06-15 23:36:04.565   impfterminservice   [inf] [70376]   Browser-Cookie generiert: *i6ww==
2021-06-15 23:36:06.787   impfterminservice   [err] [70376]   Termin konnte nicht gebucht werden: 429 {}
2021-06-15 23:36:06.787   impfterminservice   [inf] [70376]   Starte zweiten Versuch über Selenium ...
2021-06-15 23:36:06.787   impfterminservice   [inf] [70376]   Termin über Selenium buchen
2021-06-15 23:36:07.768   impfterminservice   [inf] [70376]   Vermittlungscode eintragen und Mausbewegung / Klicks simulieren. Dieser Vorgang kann einige Sekunden dauern.
2021-06-15 23:36:08.702   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (0, 0) nach (617, 930)
2021-06-15 23:36:20.509   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (617.0, 930.0) nach (432, 758)
2021-06-15 23:36:27.801   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (432.0, 758.0) nach (314, 247)
2021-06-15 23:36:35.352   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (314.0, 247.0) nach (222, 384)
2021-06-15 23:36:50.474   impfterminservice   [inf] [70376]   Simulation der Mausbewegungen gestartet. Von: (222.0, 384.0) nach (413, 450)
2021-06-15 23:36:58.375   impfterminservice   [err] [70376]   Termine können nicht gesucht werden
2021-06-15 23:37:02.635   impfterminservice   [err] [70376]   Termine können nicht ausgewählt werden
2021-06-15 23:37:03.857   impfterminservice   [err] [70376]   Termine können nicht ausgewählt werden (Button)
2021-06-15 23:37:04.906   impfterminservice   [err] [70376]   1. Daten können nicht erfasst werden
2021-06-15 23:37:05.926   impfterminservice   [err] [70376]   Kontaktdaten können nicht eingegeben werden
2021-06-15 23:37:07.196   impfterminservice   [err] [70376]   Button ÜBERNEHMEN kann nicht gedrückt werden
2021-06-15 23:37:08.251   impfterminservice   [err] [70376]   Button Termin buchen kann nicht gedrückt werden
2021-06-15 23:37:11.260   impfterminservice   [err] [70376]   Automatisierte Terminbuchung fehlgeschlagen
2021-06-15 23:37:11.261   impfterminservice   [err] [70376]   Termin manuell im Fenster oder im Browser buchen.
2021-06-15 23:37:11.261   impfterminservice   [err] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/****-****-****/70376
2021-06-15 23:47:13.431   impfterminservice   [err] [70376]   Termin konnte nicht gebucht werden.
```

```
2021-06-15 23:35:37.439   impfterminservice   [suc] [70376]   Termin gefunden!
2021-06-15 23:35:37.439   impfterminservice   [suc] [70376]   'Impfzentrum am Robert-Bosch-Krankenhaus' in 70376 Stuttgart
2021-06-15 23:35:37.439   impfterminservice   [suc] [70376]   1. Termin: 29.06.2021 um 19:45 Uhr
2021-06-15 23:35:37.439   impfterminservice   [suc] [70376]   2. Termin: 10.08.2021 um 15:10 Uhr
2021-06-15 23:35:37.439   impfterminservice   [suc] [70376]   Link: https://001-iz.impfterminservice.de/impftermine/suche/****-****-****/70376
2021-06-15 23:35:37.575   impfterminservice   [inf] [70376]   Browser-Cookies generieren
Traceback (most recent call last):
  File "D:\Repos\vaccipy\main.py", line 615, in <module>
    main()
  File "D:\Repos\vaccipy\main.py", line 515, in main
    subcommand_search(args)
  File "D:\Repos\vaccipy\main.py", line 416, in subcommand_search
    run_search_interactive(args.file, args.configure_notifications, check_delay=args.retry_sec)
  File "D:\Repos\vaccipy\main.py", line 272, in run_search_interactive
    return run_search(kontaktdaten, check_delay)
  File "D:\Repos\vaccipy\main.py", line 307, in run_search
  File "D:\Repos\vaccipy\tools\its.py", line 1342, in terminsuche
    its.termin_buchen(reservierung)
  File "D:\Repos\vaccipy\tools\its.py", line 899, in termin_buchen
    cookies = self.get_cookies(url, manual=False)
  File "D:\Repos\vaccipy\tools\its.py", line 627, in get_cookies
    driver = self.get_chromedriver(headless=False)
  File "D:\Repos\vaccipy\tools\its.py", line 295, in get_chromedriver
    return Chrome(self.get_chromedriver_path(), options=chrome_options)
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\snage\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=91.0.4472.101)
```

**Comment by nagel86** [comment]
Soeben wurde für die Person mit einem anderen Code ein neuer Termin in einem anderen Impfzentrum gefunden. Konnte wieder nicht automatisch gebucht werden, aber diesmal ging es manuell.

Ich bin daher mal so frei und mache hier zu, war evtl. einfach nur ein unglücklicher Zufall.
